site_name: TamerPlatform-KB
docs_dir: Documents
site_description: KnowledgeBase for Tamer Platform
site_author: TamerPlatform Team
site_dir: site
#theme: readthedocs
markdown_extensions:
  - markdown_newtab
  - oembed
  - markdown_checklist.extension
  - pymdownx.details
#include_next_prev: false
copyright: (c) Android Tamer Team
site_favicon: favicon.ico
theme: 'tamerdocs'
#theme_dir: mkdocs-reloaded/mkdocs-reloaded
repo_url: https://github.com/TamerPlatform
extra:
  search: false
  twitter: https://www.twitter.com/TamerPlatform
